# -*- coding: utf-8 -*-
"""
Colección de frases célebres para el widget de citas.
Puedes añadir tantas frases como quieras siguiendo el formato:
    ("La frase aquí", "Autor o Película"),

El sistema seleccionará frases aleatoriamente cada 30 segundos.
"""

QUOTES = [
    # FRASES ORIGINALES (MEDICINA)
    ("La medicina es la única profesión que trabaja día y noche para hacerse superflua.", "Karl Popper"),
    ("Donde hay amor por la medicina, hay amor por la humanidad.", "Hipócrates"),
    ("El diagnóstico es el arte de distinguir lo mismo de lo similar.", "Anónimo"),
    ("La mejor medicina es la que enseña al paciente a prescindir del médico.", "Thomas Edison"),
    ("El médico debe distinguir entre lo posible y lo imposible; en lo posible debe persistir.", "Paracelso"),
    ("Observa, registra, tabula, comunica.", "William Osler"),
    ("El diagnóstico precoz salva vidas.", "Anónimo"),
    ("La precisión en la imagen es la precisión en el diagnóstico.", "Anónimo"),
    ("La tecnología al servicio de la salud.", "Anónimo"),
    ("Cada imagen cuenta una historia; nuestro trabajo es leerla bien.", "Anónimo"),
    ("El buen médico trata la enfermedad; el gran médico trata al paciente que tiene la enfermedad.", "William Osler"),
    ("Donde quiera que se ama el arte de la medicina, se ama también a la humanidad.", "Hipócrates"),
    ("Cura a veces, trata con frecuencia, consuela siempre.", "Hipócrates"),
    ("Es más importante saber qué persona tiene la enfermedad que qué enfermedad tiene la persona.", "Hipócrates"),
    ("La vida es breve, el arte es largo, la oportunidad fugaz, la experiencia engañosa y el juicio difícil.", "Hipócrates"),
    ("Que tu alimento sea tu medicina y tu medicina sea tu alimento.", "Hipócrates"),
    ("El médico trata, pero la naturaleza sana.", "Hipócrates"),
    ("Primero, no hacer daño.", "Hipócrates"),
    ("El que sólo sabe medicina, ni medicina sabe.", "José de Letamendi"),
    ("La medicina es una ciencia de la incertidumbre y un arte de la probabilidad.", "William Osler"),
    ("El tiempo es generalmente el mejor médico.", "Ovidio"),
    ("Los mejores médicos del mundo son: el doctor dieta, el doctor reposo y el doctor alegría.", "Jonathan Swift"),
    ("El mejor médico es el que conoce la inutilidad de la mayor parte de las medicinas.", "Benjamin Franklin"),
    ("No puede el médico curar bien sin tener presente al enfermo.", "Séneca"),
    ("El médico debe ser el auxiliar de la naturaleza, no su enemigo.", "Paracelso"),
    ("La diferencia entre el remedio y el veneno es la dosis.", "Paracelso"),
    ("Mens sana in corpore sano.", "Juvenal"),
    ("No hay medicina que cure lo que no cura la felicidad.", "Gabriel García Márquez"),
    ("Cuida tu cuerpo. Es el único lugar en el que tienes que vivir.", "Jim Rohn"),
    ("El primer requisito de un hospital es que nunca debe dañar al paciente.", "Florence Nightingale"),
    ("La medicina es el arte de conservar la salud y eventualmente de curar la enfermedad ocurrida en el cuerpo.", "Paracelso"),
    ("Sólo el médico y el dramaturgo gozan del raro privilegio de cobrar las desazones que nos dan.", "Santiago Ramón y Cajal"),
    ("El cirujano vive con la muerte, es su compañera inseparable, con ella me voy de la mano.", "Anónimo médico"),
    ("Un médico concienzudo debe morir con el enfermo si no pueden sanar juntos.", "Eugène Ionesco"),
    ("No hay hombre más digno de estimación que el médico que, habiendo estudiado la naturaleza desde su juventud, conoce las propiedades del cuerpo humano.", "Voltaire"),
    ("El médico competente, antes de dar una medicina a su paciente, se familiariza no sólo con la enfermedad que desea curar, sino también con los hábitos y la constitución del enfermo.", "Cicerón"),
    ("Mil enfermos requieren mil curas.", "Ovidio"),
    ("Ser médico es tener la responsabilidad de ser la voz de la esperanza y el abrazo de la curación.", "Anónimo"),
    ("La mejor medicina de todas es enseñarle a la gente cómo no necesitarla.", "Hipócrates"),
    ("Las palabras son una medicina para el alma que sufre.", "Esquilo"),
    ("El progreso de la medicina es una de las maravillas del siglo.", "Anónimo"),
    ("Los médicos como la cerveza, mejor cuanto más viejos.", "Proverbio"),
    ("Caminar es el mejor ejercicio posible. Habitúate a caminar muy lejos.", "Thomas Jefferson"),
    ("Si no eres tu propio médico, eres un tonto.", "Hipócrates"),
    ("Tonto el médico que desprecia el conocimiento adquirido por los antiguos.", "Hipócrates"),
    ("La medicina ha avanzado tanto que ya todos estamos enfermos.", "Aldous Huxley"),
    ("La medicina es una vocación de servicio, no una simple ocupación.", "Anónimo"),
    ("Ser médico no es una profesión; es una forma de vida.", "Anónimo"),
    ("El paciente debe combatir la enfermedad junto con el médico.", "Hipócrates"),
    ("Haz un hábito de dos cosas: ayudar; o al menos no hacer daño.", "Hipócrates"),
    ("Los médicos son muchos en el título, pero muy pocos en realidad.", "Hipócrates"),
    ("La principal virtud que puede tener el lenguaje es la claridad.", "Hipócrates"),
    ("Donde hay amor por la medicina, hay amor por la humanidad.", "Platón"),
    ("El médico que no entiende de almas no entenderá cuerpos.", "José Narosky"),
    ("Un amigo fiel es la medicina de la vida.", "A.D."),
    ("La medicina es una ciencia social, y la política es nada más que medicina a gran escala.", "Rudolf Virchow"),
    ("La medicina es mi esposa legítima y la literatura mi amante ilegítima.", "Anton Chejov"),
    ("El cielo cura y el médico cobra la minuta.", "Proverbio"),
    ("Casi todos los médicos tienen su enfermedad favorita.", "Henry Fielding"),
    ("Antes de que te cases, mira lo que haces; después de casado, haz lo que mires.", "Proverbio médico"),
    ("La salud es un estado de completo bienestar físico, mental y social.", "OMS"),
    ("La prevención es mejor que la cura.", "Proverbio"),
    ("El ejercicio es la mejor medicina.", "Anónimo"),
    ("Ríe y el mundo reirá contigo; llora y llorarás solo.", "Proverbio"),
    ("La risa es la mejor medicina.", "Proverbio"),
    ("Come para vivir, no vivas para comer.", "Proverbio"),
    ("El sueño es la mejor medicina natural.", "Anónimo"),
    ("El estrés es el peor enemigo de la salud.", "Anónimo"),
    ("La felicidad es la mejor terapia.", "Anónimo"),
    ("El optimismo es el mejor medicamento.", "Anónimo"),
    ("La fe mueve montañas y cura enfermedades.", "Anónimo"),
    ("El amor es la medicina más poderosa.", "Anónimo"),
    ("La esperanza es el mejor remedio.", "Anónimo"),
    ("La paciencia es una gran medicina.", "Anónimo"),
    ("El descanso es medicina para el cuerpo.", "Anónimo"),
    ("La naturaleza es el mejor médico.", "Anónimo"),
    ("La moderación en todo es la clave de la salud.", "Anónimo"),
    ("Bebe agua como si fuera medicina.", "Anónimo"),
    ("Respira profundo, es medicina gratuita.", "Anónimo"),
    ("Sonríe, es la mejor curva de la salud.", "Anónimo"),
    ("El sol es la mejor vitamina.", "Anónimo"),
    ("La música es medicina para el alma.", "Anónimo"),
    ("Los libros son medicina para la mente.", "Anónimo"),
    ("La gratitud es la medicina del corazón.", "Anónimo"),
    ("El perdón cura heridas profundas.", "Anónimo"),
    ("La meditación es medicina moderna.", "Anónimo"),
    ("El yoga une cuerpo y mente en salud.", "Anónimo"),
    ("Caminar cura más que muchos remedios.", "Anónimo"),
    ("El baile es medicina alegre.", "Anónimo"),
    ("La amistad es medicina social.", "Anónimo"),
    ("La familia es el mejor apoyo médico.", "Anónimo"),
    ("El trabajo bien hecho cura el espíritu.", "Anónimo"),
    ("La curiosidad mantiene joven el cerebro.", "Anónimo"),
    ("Aprender algo nuevo cada día es medicina mental.", "Anónimo"),
    ("La lectura previene el Alzheimer.", "Anónimo"),
    ("El silencio es medicina para el ruido interior.", "Anónimo"),
    ("La naturaleza cura el estrés.", "Anónimo"),
    ("El mar es terapia natural.", "Anónimo"),
    ("Las montañas dan perspectiva y salud.", "Anónimo"),
    ("El bosque es oxígeno y paz.", "Anónimo"),
    ("Las plantas son medicina verde.", "Anónimo"),
    ("El té es medicina caliente.", "Anónimo"),
    ("El ajo es antibiótico natural.", "Anónimo"),
    ("La miel cura más que muchas pastillas.", "Anónimo"),
    ("El limón es vitamina C pura.", "Anónimo"),
    ("El jengibre alivia todo mal.", "Anónimo"),
    ("La cúrcuma es antiinflamatoria poderosa.", "Anónimo"),
    ("El agua con limón es elixir matutino.", "Anónimo")
    
    # EJEMPLOS DE FRASES DE PELÍCULAS (Añade más siguiendo este formato)
    ("Que la Fuerza te acompañe.", "Star Wars"),
    ("No, yo soy tu padre.", "Star Wars: El imperio contraataca"),
    ("Hazlo o no lo hagas, pero no lo intentes.", "Star Wars: El imperio contraataca"),
    ("Le haré una oferta que no podrá rechazar.", "El Padrino"),
    ("Francamente, querida, me importa un rábano.", "Lo que el viento se llevó"),
    ("¡Soy el rey del mundo!", "Titanic"),
    ("Mamá siempre decía: la vida es como una caja de chocolates, nunca sabes qué te va a tocar.", "Forrest Gump"),
    ("Hasta la vista, baby.", "Terminator 2: El juicio final"),
    ("¡Houston, tenemos un problema!", "Apolo 13"),
    ("En ocasiones veo muertos.", "El sexto sentido"),
    ("¡Hasta el infinito y más allá!", "Toy Story"),
    ("¡Mi precioso!", "El señor de los anillos: Las dos torres"),
    ("¡No puedes pasar!", "El señor de los anillos: La comunidad del anillo"),
    ("Uno para gobernarlos a todos.", "El señor de los anillos: La comunidad del anillo"),
    ("¡Por favor, no me mates! ¡Soy un pez!", "Buscando a Nemo"),
    ("Me llamo Bond… James Bond.", "Dr. No"),
    ("¡E.T., teléfono, casa!", "E.T. el extraterrestre"),
    ("¡Que empiece la partida!", "Jumanji"),
    ("¡La vida es bella!", "La vida es bella"),
    ("¡Carpe diem! Aprovechad el día, muchachos.", "El club de los poetas muertos"),
    ("¿Por qué tan serio?", "El caballero oscuro"),
    ("¡Esto es Esparta!", "300"),
    ("No hay cuchara.", "Matrix"),
    ("¡Corre, Forrest, corre!", "Forrest Gump"),
    ("¡Muéstrame el dinero!", "Jerry Maguire"),
    ("¡Prefiero morir mañana que vivir cien años sin conocerte!", "Moulin Rouge"),
    ("¡Nuestro amor es como el viento… no lo veo, pero lo siento!", "Un paseo para recordar"),
    ("¡Quiero todo de ti, para siempre, tú y yo, cada día!", "El diario de Noah"),
    ("Siempre tendremos París.", "Casablanca"),
    ("¡Presiento que esto es el comienzo de una hermosa amistad!", "Casablanca"),
    ("¡No hay lugar como el hogar!", "El mago de Oz"),
    ("¡Volveré!", "Terminator"),
    ("¡Adrian!", "Rocky"),
    ("¡Libertad!", "Braveheart"),
    ("¡No pasarán!", "La batalla de Argel"),
    ("¡Yo soy el que manda aquí!", "El bueno, el feo y el malo"),
    ("¡No contaban con mi astucia!", "El Chavo del 8 – película"),
    ("¡Se me chispoteó!", "El Chapulín Colorado – película"),
    ("¡Que viene el lobo, que viene el lobo!", "Bienvenido, Mister Marshall"),
    ("¡Bienvenido, Mister Marshall!", "Bienvenido, Mister Marshall"),
    ("¡La guerra es algo muy cómodo, se le puede echar la culpa de todo!", "La escopeta nacional"),
    ("¡Que te abrace tu puta madre!", "Torrente, el brazo tonto de la ley"),
    ("¡Pepe el toro es inocente!", "Nosotros los pobres"),
    ("¡Si quieres hacer reír a Dios, cuéntale tus planes!", "Amores perros"),
    ("¡Acuéstate con hambre, pero con la frente bien limpia!", "Vino el remolino y nos alevantó"),
    ("¡Nadie es profeta en su tierra!", "Bienvenido, Mister Marshall"),
    ("¡Oh, rayos!", "Regreso al futuro"),
    ("¡Game over, man!", "Aliens"),
    ("¡Yo soy Batman!", "Batman"),
    ("¡Te voy a hacer tragar tus palabras!", "El padrino II"),
    ("¡Amar significa no tener que decir nunca lo siento!", "Love Story"),
    ("¡Bésame como si fuera la última vez!", "Casablanca"),
    ("¡Dile que la quieres!", "Love Actually"),
    ("¡Pensamos demasiado y sentimos muy poco.", "El gran dictador"),
    ("¡Nací cuando ella me besó, morí cuando me abandonó y viví mientras me amó.", "Casablanca"),
    ("¡Elemental, mi querido Watson!", "La aventura del sabueso de los Baskerville"),
    ("¡Tócala otra vez, Sam!", "Casablanca"),
    ("¡Oh sí… el pasado puede doler. Pero puedes huir de él o aprender de él.", "El rey león"),
    ("¡Justo a tiempo!", "Volver al futuro"),
    ("¡Te quiero, amigo!", "Toy Story"),
    ("¡Prefiero haber olido su cabello… que toda una eternidad sin ella!", "Los paraguas de Cherburgo"),
    ("¡Alcalde: todos somos contingentes, pero tú eres necesario!", "Amanece, que no es poco"),
    ("¡Pablo, grábalo todo! ¡Por tu puta madre!", "[REC]"),
    ("¡Ay, caramba!", "Los Simpson – película"),
    ("¡Excelente!", "Los Simpson – película"),
    ("¡D'oh!", "Los Simpson – película"),
    ("¡Nooo!", "Star Wars"),
    ("¡Síii!", "Toy Story"),
    ("¡Te amo!", "Titanic"),
    ("¡Adiós para siempre!", "Titanic"),
    ("¡No te rindas!", "Rocky"),
    ("¡Eye of the tiger!", "Rocky III"),
    ("¡Cuando los cerdos vuelen!", "Shrek"),
    ("¡Aquí mando yo!", "Piratas del Caribe"),
    ("¡El que mucho abarca poco aprieta!", "Varios"),
    ("¡Órale!", "Coco"),
    ("¡Qué padre!", "Coco"),
    ("¡Hasta luego, cocodrilo!", "Varios"),
    ("¡No me digas!", "Shrek"),
    ("¡Te voy a romper la cara!", "Gladiador"),
    ("¡Venceremos!", "V de Vendetta"),
    ("¡El fin!", "Varios"),
    ("¡Todo lo que necesitas es amor!", "Across the Universe"),
    ("¡Que la felicidad te acompañe!", "Intocable"),
    ("¡No hay plan B!", "Heat"),
    ("¡Soy inevitable.", "Avengers: Endgame"),
    ("¡Yo soy… Iron Man!", "Avengers: Endgame"),
    ("¡Somos Groot!", "Guardianes de la Galaxia"),
    ("¡Wakanda por siempre!", "Black Panther"),
    ("¡Avengers… unidos!", "Avengers: Endgame")
    ("No hay que ir para atrás ni para darse impulso.", "Lao Tsé"),
    ("No hay caminos para la paz; la paz es el camino.", "Mahatma Gandhi"),
    ("Haz el amor y no la guerra.", "Proverbio hippie"),
    ("La vida es muy peligrosa. No por las personas que hacen el mal, sino por las que se sientan a ver lo que pasa.", "Albert Einstein"),
    ("La oscuridad no puede expulsar a la oscuridad: solo la luz puede hacerlo. El odio no puede expulsar al odio: solo el amor puede hacerlo.", "Martin Luther King"),
    ("Vivir es nacer a cada instante.", "Erich Fromm"),
    ("La vida no se ha hecho para comprenderla, sino para vivirla.", "George Santayana"),
    ("Un día sin reír es un día perdido.", "Charles Chaplin"),
    ("La innovación distingue a los líderes de los seguidores.", "Steve Jobs"),
    ("Solo sé que no sé nada.", "Sócrates"),
    ("Pienso, luego existo.", "René Descartes"),
    ("El amor está compuesto por un alma habitando dos cuerpos.", "Aristóteles"),
    ("Lo que se hace por amor está más allá del bien y del mal.", "Friedrich Nietzsche"),
    ("El amor no mira con los ojos, sino con el alma.", "William Shakespeare"),
    ("Te quiero no por quien eres, sino por quien soy cuando estoy contigo.", "Gabriel García Márquez"),
    ("Estar contigo o no estar contigo es la medida de mi tiempo.", "Jorge Luis Borges"),
    ("Amar y sufrir es, a la larga, la única forma de vivir con plenitud y dignidad.", "Gregorio Marañón"),
    ("Lo que no te mata, te hace más fuerte.", "Friedrich Nietzsche"),
    ("La vida es lo que pasa mientras estás ocupado haciendo otros planes.", "John Lennon"),
    ("Carpe diem. Aprovechad el día.", "Horacio"),
    ("El éxito no es definitivo; el fracaso no es fatal: lo que cuenta es el coraje de continuar.", "Winston Churchill"),
    ("Sé el cambio que quieres ver en el mundo.", "Mahatma Gandhi"),
    ("La imaginación es más importante que el conocimiento.", "Albert Einstein"),
    ("Solo los soñadores mueven montañas.", "Fitzcarraldo"),
    ("Con un gran poder viene una gran responsabilidad.", "Spider-Man"),
    ("Lo que hacemos en la vida tiene su eco en la eternidad.", "Gladiator"),
    ("Prefiero morir de pie que vivir de rodillas.", "Emiliano Zapata"),
    ("La libertad no necesita alas, lo que necesita es espacio.", "Anónimo"),
    ("El que mucho abarca poco aprieta.", "Proverbio"),
    ("Más vale pájaro en mano que ciento volando.", "Proverbio"),
    ("A caballo regalado no le mires el diente.", "Proverbio"),
    ("No por mucho madrugar amanece más temprano.", "Proverbio"),
    ("Al mal tiempo buena cara.", "Proverbio"),
    ("Cada loco con su tema.", "Proverbio"),
    ("A buen entendedor pocas palabras bastan.", "Proverbio"),
    ("El que espera desespera.", "Proverbio"),
    ("Dios aprieta pero no ahoga.", "Proverbio"),
    ("No hay mal que por bien no venga.", "Proverbio"),
    ("A grandes males, grandes remedios.", "Proverbio"),
    ("En boca cerrada no entran moscas.", "Proverbio"),
    ("El que ríe último ríe mejor.", "Proverbio"),
    ("Más sabe el diablo por viejo que por diablo.", "Proverbio"),
    ("Perro que ladra no muerde.", "Proverbio"),
    ("Cría cuervos y te sacarán los ojos.", "Proverbio"),
    ("Dime con quién andas y te diré quién eres.", "Proverbio"),
    ("El dinero no hace la felicidad, pero ayuda.", "Proverbio"),
    ("El tiempo todo lo cura.", "Proverbio"),
    ("Ojos que no ven, corazón que no siente.", "Proverbio"),
    ("A enemigo que huye, puente de plata.", "Proverbio"),
    ("La curiosidad mató al gato.", "Proverbio"),
    ("El que no llora no mama.", "Proverbio"),
    ("A palabras necias, oídos sordos.", "Proverbio"),
    ("No todo lo que brilla es oro.", "Proverbio"),
    ("El que nada arriesga nada gana.", "Proverbio"),
    ("Más vale tarde que nunca.", "Proverbio"),
    ("El hábito hace al monje.", "Proverbio"),
    ("A río revuelto, ganancia de pescadores.", "Proverbio"),
    ("El que se quema con leche ve la vaca y llora.", "Proverbio"),
    ("No dejes para mañana lo que puedas hacer hoy.", "Proverbio"),
    ("El que siembra vientos recoge tempestades.", "Proverbio"),
    ("La unión hace la fuerza.", "Proverbio"),
    ("El que mucho habla mucho yerra.", "Proverbio"),
    ("A mal tiempo, buena letra.", "Proverbio"),
    ("El que se pica ajos come.", "Proverbio"),
    ("Dios los cría y ellos se juntan.", "Proverbio"),
    ("A falta de pan, buenas son tortas.", "Proverbio"),
    ("El que canta sus males espanta.", "Proverbio"),
    ("No hay peor ciego que el que no quiere ver.", "Proverbio"),
    ("El que calla otorga.", "Proverbio"),
    ("A cada cerdo le llega su San Martín.", "Proverbio"),
    ("El que roba al ladrón tiene cien años de perdón.", "Proverbio"),
    ("Más vale solo que mal acompañado.", "Proverbio"),
    ("El que a hierro mata a hierro muere.", "Proverbio"),
    ("No hay peor sordo que el que no quiere oír.", "Proverbio"),
    ("El tiempo es oro.", "Proverbio"),
    ("A palabras necias, oídos sordos.", "Proverbio"),
    ("La risa es la mejor medicina.", "Proverbio"),
    ("El optimismo es la fe en acción.", "Anónimo"),
    ("La esperanza es lo último que se pierde.", "Proverbio"),
    ("El amor todo lo puede.", "Proverbio"),
    ("El amor es ciego.", "Proverbio"),
    ("En el amor y en la guerra todo vale.", "Proverbio"),
    ("El amor entra por los ojos.", "Proverbio"),
    ("Amor con amor se paga.", "Proverbio"),
    ("El primer amor nunca se olvida.", "Proverbio"),
    ("Amor de lejos, amor de pendejos.", "Proverbio popular"),
    ("El amor verdadero no tiene fin.", "Anónimo"),
    ("Solo se ama lo que se conoce.", "Anónimo"),
    ("El amor es un fuego que arde sin ser visto.", "Luis de Camões"),
    ("Amar es sufrir, no amar es morir.", "Anónimo"),
    ("El amor es la única locura de los cuerdos.", "Anónimo"),
    ("El amor es un sentimiento que no se puede explicar.", "Anónimo"),
    ("Te amo no solo por lo que eres, sino por lo que soy cuando estoy contigo.", "Roy Croft"),
    ("El amor no consiste en mirarse el uno al otro, sino en mirar juntos en la misma dirección.", "Antoine de Saint-Exupéry"),
    ("El amor es eterno mientras dura.", "François de La Rochefoucauld"),
    ("Amar es no tener que decir nunca lo siento.", "Love Story"),
    ("Nuestro amor es como el viento, no lo veo pero lo siento.", "Un paseo para recordar"),
    ("Quiero todo de ti, para siempre, tú y yo cada día.", "El diario de Noah"),
    ("Prefiero morir mañana que vivir cien años sin conocerte.", "Moulin Rouge"),
    ("Bésame como si fuera la última vez.", "Casablanca"),
    ("Siempre tendremos París.", "Casablanca"),
    ("Presiento que esto es el comienzo de una hermosa amistad.", "Casablanca"),
    ("La vida es bella.", "La vida es bella"),
    ("Pensamos demasiado y sentimos muy poco.", "El gran dictador"),
    ("Nací cuando ella me besó, morí cuando me abandonó y viví mientras me amó.", "Casablanca"),
    ("El que quiere interesar a los demás tiene que provocarlos.", "Salvador Dalí"),
    ("Todos los niños nacen artistas. El problema es cómo seguir siendo artistas al crecer.", "Pablo Picasso"),
    ("La pluma es la lengua del alma.", "Miguel de Cervantes"),
    ("La vida es un frenesí, una ilusión, una sombra, una ficción.", "Calderón de la Barca"),
    ("Ser o no ser, esa es la cuestión.", "William Shakespeare"),
    ("Ser grande es perdonar siempre.", "Anónimo"),
    ("El conocimiento es poder.", "Francis Bacon"),
    ("El amor inmaduro dice: te amo porque te necesito. El maduro dice: te necesito porque te amo.", "Anónimo"),
    ("Daría todo lo que sé por la mitad de lo que ignoro.", "Anónimo"),
    ("No juzgamos a las personas que amamos.", "Jean-Paul Sartre"),
    ("El hombre es el único animal que tropieza dos veces con la misma piedra.", "Proverbio"),
    ("El que no arriesga no gana.", "Proverbio"),
    ("La vida es corta, vive intensamente.", "Anónimo"),
    ("El éxito es ir de fracaso en fracaso sin perder el entusiasmo.", "Winston Churchill"),
    ("El fracaso es el condimento que da sabor al éxito.", "Truman Capote"),
    ("No hay atajos para llegar a ningún lugar que valga la pena.", "Anónimo"),
    ("El único modo de hacer un gran trabajo es amar lo que haces.", "Steve Jobs"),
    ("Si puedes soñarlo, puedes hacerlo.", "Walt Disney"),
    ("El futuro pertenece a quienes creen en la belleza de sus sueños.", "Eleanor Roosevelt"),
    ("La mejor venganza es un éxito rotundo.", "Frank Sinatra"),
    ("No esperes. El momento nunca será perfecto.", "Napoleon Hill"),
    ("La disciplina es el puente entre metas y logros.", "Jim Rohn"),
    ("El coraje no es la ausencia de miedo, sino el triunfo sobre él.", "Nelson Mandela"),
    ("La persistencia es lo que convierte lo imposible en posible.", "Anónimo"),
    ("El único límite a nuestra realización de mañana son nuestras dudas de hoy.", "Franklin D. Roosevelt"),
    ("Cambia tu forma de pensar y cambiarás tu mundo.", "Norman Vincent Peale"),
    ("La felicidad no es algo que se pospone para el futuro; es algo que se diseña para el presente.", "Jim Rohn"),
    ("Vive como si fueras a morir mañana. Aprende como si fueras a vivir para siempre.", "Mahatma Gandhi"),
    ("El secreto de la vida es tener curiosidad.", "Anónimo"),
    ("La vida comienza al final de tu zona de confort.", "Neale Donald Walsch"),
    ("Sé tú mismo; los demás puestos ya están ocupados.", "Oscar Wilde"),
    ("La autenticidad es la clave del éxito.", "Anónimo"),
    ("El tiempo es el recurso más valioso.", "Anónimo"),
    ("Haz lo que amas y nunca trabajarás un día en tu vida.", "Confucio"),
    ("La excelencia no es un acto, es un hábito.", "Aristóteles"),
    ("El viaje de mil millas comienza con un paso.", "Lao Tsé"),
    ("La mente es todo. Lo que piensas, en eso te conviertes.", "Buda"),
    ("La paz viene de dentro. No la busques fuera.", "Buda"),
    ("La felicidad depende de nosotros mismos.", "Aristóteles"),
    ("El conocimiento libera al alma.", "Anónimo"),
    ("La verdadera libertad es dominarse a uno mismo.", "Anónimo"),
    ("El amor propio es el comienzo de una historia de amor eterna.", "Oscar Wilde"),
    ("La gratitud es la memoria del corazón.", "Anónimo"),
    ("La simplicidad es la máxima sofisticación.", "Leonardo da Vinci"),
    ("La belleza está en los ojos del que mira.", "Oscar Wilde"),
    ("El arte es la mentira que nos permite comprender la verdad.", "Pablo Picasso"),
    ("La creatividad es inteligencia divirtiéndose.", "Albert Einstein"),
    ("La música es el lenguaje de los dioses.", "Anónimo"),
    ("La poesía es el ritmo de la vida.", "Anónimo"),
    ("Los libros son amigos que nunca decepcionan.", "Anónimo"),
    ("Leer es viajar sin moverse del sillón.", "Anónimo"),
    ("Un libro es un sueño que se tiene despierto.", "Anónimo"),
    ("La educación es el arma más poderosa para cambiar el mundo.", "Nelson Mandela"),
    ("El aprendizaje nunca agota la mente.", "Leonardo da Vinci"),
    ("La curiosidad es la chispa del conocimiento.", "Anónimo"),
    ("El maestro aparece cuando el alumno está listo.", "Proverbio"),
    ("La sabiduría comienza en el asombro.", "Sócrates"),
    ("El que sabe no habla; el que habla no sabe.", "Lao Tsé"),
    ("La humildad es la base de todas las virtudes.", "Anónimo"),
    ("La paciencia es amarga, pero sus frutos son dulces.", "Aristóteles"),
    ("La perseverancia vence lo que la suerte no alcanza.", "Anónimo"),
    ("El esfuerzo sin talento es una situación deprimente, pero el talento sin esfuerzo es una tragedia.", "Anónimo"),
    ("La victoria pertenece al más perseverante.", "Napoleón Bonaparte"),
    ("El coraje es resistencia al miedo, dominio del miedo, no ausencia de miedo.", "Mark Twain"),
    ("El miedo es el camino hacia el lado oscuro.", "Yoda"),
    ("La fuerza está en la unión.", "Anónimo"),
    ("Juntos somos más fuertes.", "Anónimo"),
    ("La amistad duplica las alegrías y divide las penas.", "Proverbio"),
    ("Un amigo fiel es la mejor medicina.", "Anónimo"),
    ("Los verdaderos amigos son aquellos que entran cuando los demás salen.", "Anónimo"),
    ("La amistad es un alma en dos cuerpos.", "Aristóteles"),
    ("Los amigos son la familia que elegimos.", "Anónimo"),
    ("En la amistad no hay mañana ni ayer.", "Anónimo"),
    ("La lealtad es el sello de la amistad verdadera.", "Anónimo"),
    ("Un amigo es alguien que sabe todo de ti y aún así te quiere.", "Anónimo"),
    ("La risa es el idioma universal de las almas.", "Anónimo"),
    ("Ríe y el mundo reirá contigo.", "Proverbio"),
    ("La alegría es contagiosa.", "Anónimo"),
    ("Sé feliz en este momento. Este momento es tu vida.", "Omar Khayyam"),
    ("La vida es corta, sonríe mientras aún tienes dientes.", "Anónimo"),
    ("La felicidad no es tener lo que quieres, sino querer lo que tienes.", "Anónimo"),
    ("La gratitud convierte lo que tenemos en suficiente.", "Anónimo"),
    ("El presente es el único tiempo real.", "Anónimo"),
    ("Vive el ahora.", "Anónimo"),
    ("El ayer es historia, el mañana es un misterio, hoy es un regalo.", "Anónimo"),
    ("Cada día es una nueva oportunidad.", "Anónimo"),
    ("El sol sale para todos.", "Proverbio"),
    ("Después de la tormenta viene la calma.", "Proverbio"),
    ("Todo pasa.", "Anónimo"),
    ("El tiempo cura todo.", "Proverbio"),
    ("La vida sigue.", "Anónimo"),
    ("Levántate, sacúdete el polvo y sigue adelante.", "Anónimo"),
    ("Caer siete veces, levantarse ocho.", "Proverbio japonés"),
    ("El fracaso es solo una oportunidad para empezar de nuevo.", "Henry Ford"),
    ("No hay fracaso, solo feedback.", "Anónimo"),
    ("El éxito es la suma de pequeños esfuerzos repetidos día tras día.", "Robert Collier"),
    ("La constancia vence lo que la dicha no alcanza.", "Anónimo"),
    ("La disciplina pesa pocos kilos, el arrepentimiento toneladas.", "Anónimo"),
    ("El dolor es temporal, la gloria eterna.", "Anónimo"),
    ("Sin dolor no hay ganancia.", "Proverbio"),
    ("El sudor es la esencia del éxito.", "Anónimo"),
    ("Trabaja duro en silencio, deja que el éxito haga ruido.", "Anónimo"),
    ("El éxito no llega por casualidad.", "Anónimo"),
    ("Cree en ti mismo y todo será posible.", "Anónimo"),
    ("Tú puedes.", "Anónimo"),
    ("El poder está en tu mente.", "Anónimo"),
    ("La mente lo logra todo.", "Anónimo"),
    ("Sé el cambio.", "Mahatma Gandhi"),
    ("Cambia tu pensamiento y cambiarás tu mundo.", "Anónimo"),
    ("La actitud lo es todo.", "Anónimo"),
    ("Positivo atrae positivo.", "Anónimo"),
    ("La energía fluye donde va la atención.", "Anónimo"),
    ("Visualiza el éxito.", "Anónimo"),
    ("Sueña en grande.", "Anónimo"),
    ("Los sueños se cumplen cuando actúas.", "Anónimo"),
    ("Actúa como si ya lo hubieras logrado.", "Anónimo"),
    ("La fe mueve montañas.", "Proverbio"),
    ("Cree y lo verás.", "Anónimo"),
    ("La esperanza nunca muere.", "Anónimo"),
    ("Mantén la fe.", "Anónimo"),
    ("Todo es posible para el que cree.", "Anónimo"),
    ("El universo conspira a tu favor.", "Paulo Coelho"),
    ("Sigue tu corazón.", "Anónimo"),
    ("Escucha tu intuición.", "Anónimo"),
    ("Tu intuición sabe más que tú.", "Anónimo"),
    ("Confía en el proceso.", "Anónimo"),
    ("Todo sucede por una razón.", "Anónimo"),
    ("Acepta lo que es.", "Anónimo"),
    ("Suelta lo que no puedes controlar.", "Anónimo"),
    ("La paz interior es la verdadera riqueza.", "Anónimo"),
    ("Sé amable contigo mismo.", "Anónimo"),
    ("El amor propio es clave.", "Anónimo"),
    ("Perdónate y avanza.", "Anónimo"),
    ("El perdón libera el alma.", "Anónimo"),
    ("Suelta el rencor.", "Anónimo"),
    ("Vive sin arrepentimientos.", "Anónimo"),
    ("Haz lo que te haga feliz.", "Anónimo"),
    ("La felicidad es una elección.", "Anónimo"),
    ("Elige ser feliz.", "Anónimo"),
    ("Sonríe al mundo.", "Anónimo"),
    ("La sonrisa abre puertas.", "Anónimo"),
    ("La bondad regresa multiplicada.", "Anónimo"),
    ("Da sin esperar nada.", "Anónimo"),
    ("La generosidad enriquece.", "Anónimo"),
    ("Ayuda y serás ayudado.", "Anónimo"),
    ("El servicio es el alquiler que pagamos por vivir.", "Anónimo"),
    ("Sé útil.", "Anónimo"),
    ("Haz el bien sin mirar a quién.", "Proverbio"),
    ("La caridad bien entendida empieza por uno mismo.", "Proverbio"),
    ("Ama al prójimo como a ti mismo.", "Biblia"),
    ("Trata a los demás como quieres ser tratado.", "Proverbio"),
    ("La empatía une corazones.", "Anónimo"),
    ("Entiende antes de ser entendido.", "Anónimo"),
    ("Escucha activamente.", "Anónimo"),
    ("Las palabras curan o matan.", "Anónimo"),
    ("Habla con amor.", "Anónimo"),
    ("El silencio es oro.", "Proverbio"),
    ("Piensa antes de hablar.", "Anónimo"),
    ("Las palabras tienen poder.", "Anónimo"),
    ("Di la verdad aunque duela.", "Anónimo"),
    ("La honestidad es la mejor política.", "Proverbio"),
    ("Sé íntegro.", "Anónimo"),
    ("La integridad es hacer lo correcto cuando nadie mira.", "Anónimo"),
    ("El carácter se construye en la adversidad.", "Anónimo"),
    ("Las dificultades forjan el carácter.", "Anónimo"),
    ("Lo que no te mata te fortalece.", "Friedrich Nietzsche"),
    ("La resiliencia es clave.", "Anónimo"),
    ("Levántate más fuerte.", "Anónimo"),
    ("Cada caída es una lección.", "Anónimo"),
    ("Aprende de los errores.", "Anónimo"),
    ("El error es maestro.", "Anónimo"),
    ("La experiencia es la madre de la ciencia.", "Proverbio"),
    ("La sabiduría viene con los años.", "Proverbio"),
    ("Nunca es tarde para aprender.", "Anónimo"),
    ("El aprendizaje dura toda la vida.", "Anónimo"),
    ("Mantén la mente abierta.", "Anónimo"),
    ("La flexibilidad es fuerza.", "Anónimo"),
    ("Adáptate o perece.", "Anónimo"),
    ("El cambio es la única constante.", "Heráclito"),
    ("Abraza el cambio.", "Anónimo"),
    ("El futuro es ahora.", "Anónimo"),
    ("Vive el presente.", "Anónimo"),
    ("El ahora es todo lo que tienes.", "Anónimo"),
    ("Disfruta cada momento.", "Anónimo"),
    ("La vida es un regalo.", "Anónimo"),
    ("Agradece cada día.", "Anónimo"),
    ("La gratitud multiplica lo bueno.", "Anónimo"),
    ("Cuenta tus bendiciones.", "Anónimo"),
    ("Sé agradecido.", "Anónimo"),
    ("La abundancia está en la mente.", "Anónimo"),
    ("Piensa en grande.", "Anónimo"),
    ("El universo es abundante.", "Anónimo"),
    ("Atrae lo que emites.", "Anónimo"),
    ("Vibra alto.", "Anónimo"),
    ("La positividad transforma.", "Anónimo"),
    ("Sé luz.", "Anónimo"),
    ("Ilumina el mundo.", "Anónimo"),
    ("El mundo necesita tu brillo.", "Anónimo"),
    ("Sé tú.", "Anónimo"),
    ("Tu autenticidad inspira.", "Anónimo"),
    ("Sé valiente.", "Anónimo"),
    ("El coraje es contagioso.", "Anónimo"),
    ("Vive sin miedo.", "Anónimo"),
    ("Enfrenta tus miedos.", "Anónimo"),
    ("El miedo es ilusión.", "Anónimo"),
    ("Supera tus límites.", "Anónimo"),
    ("Rompe barreras.", "Anónimo"),
    ("Tú eres capaz.", "Anónimo"),
    ("Cree en tu potencial.", "Anónimo"),
    ("Tu potencial es ilimitado.", "Anónimo"),
    ("Expande tus horizontes.", "Anónimo"),
    ("Explora.", "Anónimo"),
    ("Atrévete.", "Anónimo"),
    ("Sal de tu zona de confort.", "Anónimo"),
    ("La aventura espera.", "Anónimo"),
    ("Vive intensamente.", "Anónimo"),
    ("Siente todo.", "Anónimo"),
    ("Ama con pasión.", "Anónimo"),
    ("Vive con pasión.", "Anónimo"),
    ("La pasión mueve montañas.", "Anónimo"),
    ("Encuentra tu propósito.", "Anónimo"),
    ("Vive con propósito.", "Anónimo"),
    ("Tu misión es única.", "Anónimo"),
    ("Deja huella.", "Anónimo"),
    ("Haz la diferencia.", "Anónimo"),
    ("El mundo es mejor contigo.", "Anónimo"),
    ("Sé extraordinario.", "Anónimo"),
    ("Brilla.", "Anónimo"),
    ("El fin.", "Varios")
]
