# -*- coding: utf-8 -*-
"""
Colección de frases célebres para el widget de citas.
Puedes añadir tantas frases como quieras siguiendo el formato:
    ("La frase aquí", "Autor o Película"),

El sistema seleccionará frases aleatoriamente cada 30 segundos.
"""

QUOTES = [
    # FRASES ORIGINALES (MEDICINA)
    ("La medicina es la única profesión que trabaja día y noche para hacerse superflua.", "Karl Popper"),
    ("Donde hay amor por la medicina, hay amor por la humanidad.", "Hipócrates"),
    ("El diagnóstico es el arte de distinguir lo mismo de lo similar.", "Anónimo"),
    ("La mejor medicina es la que enseña al paciente a prescindir del médico.", "Thomas Edison"),
    ("El médico debe distinguir entre lo posible y lo imposible; en lo posible debe persistir.", "Paracelso"),
    ("Observa, registra, tabula, comunica.", "William Osler"),
    ("El diagnóstico precoz salva vidas.", "Anónimo"),
    ("La precisión en la imagen es la precisión en el diagnóstico.", "Anónimo"),
    ("La tecnología al servicio de la salud.", "Anónimo"),
    ("Cada imagen cuenta una historia; nuestro trabajo es leerla bien.", "Anónimo"),
    
    # EJEMPLOS DE FRASES DE PELÍCULAS (Añade más siguiendo este formato)
    ("Que la Fuerza te acompañe.", "Star Wars"),
    ("Soy tu padre.", "Star Wars: El Imperio Contraataca"),
    ("Hazlo o no lo hagas, pero no lo intentes.", "Star Wars: El Imperio Contraataca"),
    ("El miedo lleva a la ira, la ira lleva al odio, el odio lleva al sufrimiento.", "Star Wars: La Amenaza Fantasma"),
    ("No hay lugar como el hogar.", "El Mago de Oz"),
    ("Con gran poder viene gran responsabilidad.", "Spider-Man"),
    ("Soy Batman.", "The Dark Knight"),
    ("Algunos hombres solo quieren ver arder el mundo.", "The Dark Knight"),
    ("¿Por qué tan serio?", "The Dark Knight"),
    ("La vida es como una caja de bombones, nunca sabes lo que te va a tocar.", "Forrest Gump"),
    ("Corre, Forrest, corre.", "Forrest Gump"),
    ("Houston, tenemos un problema.", "Apollo 13"),
    ("I'll be back.", "Terminator"),
    ("Hasta la vista, baby.", "Terminator 2"),
    ("Bond. James Bond.", "James Bond"),
    ("Shaken, not stirred.", "James Bond"),
    ("Lo esencial es invisible a los ojos.", "El Principito"),
    ("Eres responsable para siempre de lo que has domesticado.", "El Principito"),
    ("Here's looking at you, kid.", "Casablanca"),
    ("We'll always have Paris.", "Casablanca"),
    ("Louis, creo que este es el comienzo de una hermosa amistad.", "Casablanca"),
    ("Frankly, my dear, I don't give a damn.", "Lo que el viento se llevó"),
    ("I love you. I know.", "Star Wars: El Imperio Contraataca"),
    ("May the Force be with you.", "Star Wars"),
    ("Do or do not. There is no try.", "Star Wars: El Imperio Contraataca"),
    ("I am your father.", "Star Wars: El Imperio Contraataca"),
    ("It's a trap!", "Star Wars: El Retorno del Jedi"),
    ("Hasta la vista, baby.", "Terminator 2"),
    ("Come with me if you want to live.", "Terminator 2"),
    ("I see dead people.", "El Sexto Sentido"),
    ("Show me the money!", "Jerry Maguire"),
    ("You had me at hello.", "Jerry Maguire"),
    ("You complete me.", "Jerry Maguire"),
    ("My name is Inigo Montoya. You killed my father. Prepare to die.", "La Princesa Prometida"),
    ("As you wish.", "La Princesa Prometida"),
    ("Inconceivable!", "La Princesa Prometida"),
    ("On Wednesdays we wear pink.", "Chicas Pesadas"),
    ("That's so fetch!", "Chicas Pesadas"),
    ("You can't sit with us.", "Chicas Pesadas"),
    ("Get in, loser. We're going shopping.", "Chicas Pesadas"),
    ("Just keep swimming.", "Buscando a Nemo"),
    ("To infinity and beyond!", "Toy Story"),
    ("There's a snake in my boot!", "Toy Story"),
    ("I'll have what she's having.", "Cuando Harry encontró a Sally"),
    ("You're gonna need a bigger boat.", "Tiburón"),
    ("Go ahead, make my day.", "Sudden Impact"),
    ("I am serious. And don't call me Shirley.", "Airplane!"),
    ("May the Schwartz be with you!", "Spaceballs"),
    ("I'm surrounded by Assholes!", "Spaceballs"),
    ("We are Groot.", "Guardianes de la Galaxia"),
    ("I am Groot.", "Guardianes de la Galaxia"),
    ("Why is Gamora?", "Avengers: Infinity War"),
    ("I am Iron Man.", "Iron Man / Avengers: Endgame"),
    ("Love you 3000.", "Avengers: Endgame"),
    ("Avengers Assemble!", "Avengers: Endgame"),
    ("I can do this all day.", "Capitán América"),
    ("I'm always angry.", "The Avengers"),
    ("Puny god.", "The Avengers"),
    ("Dormammu, I've come to bargain.", "Doctor Strange"),
    ("Wakanda forever!", "Black Panther"),
    ("Get this man a shield.", "Avengers: Infinity War"),
    ("I am inevitable.", "Avengers: Endgame"),
    ("Part of the journey is the end.", "Avengers: Endgame"),
    ("Whatever it takes.", "Avengers: Endgame"),
    ("No amount of money ever bought a second of time.", "Avengers: Endgame"),
    ("I went for the head.", "Avengers: Endgame"),
    ("I know.", "Star Wars: El Imperio Contraataca"),
    ("Never tell me the odds.", "Star Wars: El Imperio Contraataca"),
    ("Do. Or do not. There is no try.", "Star Wars: El Imperio Contraataca"),
    ("Your eyes can deceive you. Don't trust them.", "Star Wars"),
    ("In my experience there is no such thing as luck.", "Star Wars"),
    ("Great, kid. Don't get cocky.", "Star Wars"),
    ("This is the way.", "The Mandalorian"),
    ("I have spoken.", "The Mandalorian"),
    
    # AÑADE TUS PROPIAS FRASES AQUÍ SIGUIENDO EL FORMATO:
    # ("Tu frase aquí", "Autor o Película"),
    # ("Otra frase", "Autor"),
    
]
